### ISSUE TITLE
Dashboard UI

### ISSUE THREAD

**Issue by Alsadi30** [Alsadi30/devs-corner#1]

**Comment by afmssrahi** [comment]
Dashboard UI workflow running in Figma

**Comment by afmssrahi** [comment]
Dashboard UI in Figma is done.
https://www.figma.com/proto/BqZffIdxFbkIICvETdD6oY/Dev's-Corner-Dashboard?node-id=62%3A127&scaling=scale-down&page-id=0%3A1
